/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as authorizedLayoutRouteImport } from './routes/(authorized)/_layout'
import { Route as authorizedLayoutWeatherRouteImport } from './routes/(authorized)/_layout/weather'
import { Route as authorizedLayoutUserRouteImport } from './routes/(authorized)/_layout/user'

const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedLayoutRoute = authorizedLayoutRouteImport.update({
  id: '/(authorized)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedLayoutWeatherRoute = authorizedLayoutWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => authorizedLayoutRoute,
} as any)
const authorizedLayoutUserRoute = authorizedLayoutUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => authorizedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/user': typeof authorizedLayoutUserRoute
  '/weather': typeof authorizedLayoutWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/user': typeof authorizedLayoutUserRoute
  '/weather': typeof authorizedLayoutWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/(authorized)/_layout': typeof authorizedLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/(authorized)/_layout/user': typeof authorizedLayoutUserRoute
  '/(authorized)/_layout/weather': typeof authorizedLayoutWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/auth/login'
    | '/auth/register'
    | '/user'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/auth/login'
    | '/auth/register'
    | '/user'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/forbidden'
    | '/(authorized)/_layout'
    | '/auth/login'
    | '/auth/register'
    | '/(authorized)/_layout/user'
    | '/(authorized)/_layout/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForbiddenRoute: typeof ForbiddenRoute
  authorizedLayoutRoute: typeof authorizedLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)/_layout': {
      id: '/(authorized)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)/_layout/weather': {
      id: '/(authorized)/_layout/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof authorizedLayoutWeatherRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/_layout/user': {
      id: '/(authorized)/_layout/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof authorizedLayoutUserRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
  }
}

interface authorizedLayoutRouteChildren {
  authorizedLayoutUserRoute: typeof authorizedLayoutUserRoute
  authorizedLayoutWeatherRoute: typeof authorizedLayoutWeatherRoute
}

const authorizedLayoutRouteChildren: authorizedLayoutRouteChildren = {
  authorizedLayoutUserRoute: authorizedLayoutUserRoute,
  authorizedLayoutWeatherRoute: authorizedLayoutWeatherRoute,
}

const authorizedLayoutRouteWithChildren =
  authorizedLayoutRoute._addFileChildren(authorizedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForbiddenRoute: ForbiddenRoute,
  authorizedLayoutRoute: authorizedLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
